# Generated by Django 2.2.1 on 2019-11-07 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RealState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='application/img')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserva.City')),
                ('owner', models.ForeignKey(on_delete=models.SET('null'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('code', models.IntegerField()),
                ('total', models.IntegerField()),
                ('RealState', models.ForeignKey(on_delete=models.SET('null'), to='reserva.RealState')),
            ],
        ),
        migrations.CreateModel(
            name='RentDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('RealState', models.ForeignKey(on_delete=models.SET('null'), to='reserva.RealState')),
                ('reservation', models.ForeignKey(on_delete=models.SET('null'), to='reserva.Reservation')),
            ],
        ),
    ]
