# Generated by Django 2.2.1 on 2019-11-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_auto_20191108_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='RealState',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
