# Generated by Django 2.2.1 on 2019-11-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_auto_20191113_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('dateFrom', models.DateTimeField()),
                ('dateTo', models.DateTimeField()),
            ],
        ),
    ]
