# Generated by Django 2.2.1 on 2019-11-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_rentform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentform',
            old_name='dateFrom',
            new_name='Desde',
        ),
        migrations.RenameField(
            model_name='rentform',
            old_name='dateTo',
            new_name='Hasta',
        ),
        migrations.RenameField(
            model_name='rentform',
            old_name='name',
            new_name='Nombre',
        ),
    ]
