# Generated by Django 2.2.1 on 2019-11-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_auto_20191113_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentform',
            name='Desde',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rentform',
            name='Hasta',
            field=models.DateField(),
        ),
    ]
