# Generated by Django 2.2.1 on 2019-11-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_auto_20191113_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentForm',
        ),
        migrations.AlterField(
            model_name='rentdate',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=models.SET('null'), to='reserva.Reservation'),
        ),
    ]
