# Generated by Django 2.2.1 on 2019-11-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_auto_20191113_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdate',
            name='RealState',
            field=models.ForeignKey(on_delete=models.SET('null'), related_name='rents', to='reserva.RealState'),
        ),
        migrations.AlterField(
            model_name='rentdate',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=models.SET('null'), related_name='rents', to='reserva.Reservation'),
        ),
    ]
