# Generated by Django 2.2.1 on 2019-11-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0008_auto_20191113_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdate',
            name='reservation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET('null'), related_name='rents', to='reserva.Reservation'),
        ),
    ]
