# Generated by Django 2.2.1 on 2019-11-15 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_auto_20191113_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdate',
            name='date',
            field=models.DateField(),
        ),
    ]
